- name: roboshop instance management
  hosts: local
  connection: local
  vars:
    instances: mongodb-test-instance
  tasks: 
  - name: Create instance 
    amazon.aws.ec2_instance:
      name: "mongodb"
      instance_type: t3.micro
      security_group: default
      image_id: ami-0220d79f3f480ecf5
      tags:
        Environment: UAT

  
  