- name: roboshop instance management
  hosts: localhost
  connection: local
  vars:
    instances: mongodb-test-instance
  tasks: 
  - name: Create instance 
    amazon.aws.ec2_instance:
      name: "mongodb"
      region: us-east-1
      instance_type: t3.micro
      security_group: default
      image_id: ami-0220d79f3f480ecf5
      tags:
        Environment: UAT

  tasks: 
  - name: deleteinstance 
    amazon.aws.ec2_instance:
      state: absent
      name: "mongodb"
      wait: false
      region: us-east-1

  